name: Java CI with Gradle # workflow 이름

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make application.yml
        run: |
          # create application.yml
          cd ./back-end/src/main
          cd ./resources
          
          # application.yml 파일 생성하기
          touch ./application.yml
          
          # Secrets에 저장한 값을 application.yml 파일에 쓰기
          echo "${{ secrets.DATABASE }}" >> ./application.yml

        shell: bash

      - name: Build with Gradle
        run: |
          cd ./back-end
          ./gradlew bootJar
      ## 도커 로그인
      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      ## 도커 이미지 빌드 후 도커허브에 push하기가
      ## 테스트용 도커 이미지 삭제하기
      - name: web docker build and push
        run: |
          cd ./back-end
          docker build -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}

      ## 서버에 접속하여 도커 이미지를 pull 받고 실행하기
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo docker stop prod-server
            sudo docker rm prod-server
            sudo docker image rm ${{ secrets.DOCKER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPO }}
